### ISSUE TITLE
Plugin always triggers Kirby’s changes warning

### ISSUE THREAD

**Issue by maxhoffmann** [philippoehrlein/kirby-navigation-groups#1]
Hey, thanks for building this plugin! I’m using it in a project, where I’ve added `navigationgroups` to `site.yml`.

```
      - width: 1/3
        fields:
          navigation:
            label: Navigation
            type: navigationgroups
```

Unfortunately Kirby always displays a warning, that there are unsaved changes, when this plugin is used. If I click on save/cancel the changes, then the message is gone. But if I reload the page or navigate away and back, the message appears again, although I didn’t change anything.

Removing this plugin also stops the unsaved changes message to appear. It looks like this plugin doesn’t play well with Kirby’s change detection.

Any ideas how this can be fixed?
