### ISSUE TITLE
Can't figure out how to add page or link

### ISSUE THREAD

**Issue by andykamezou** [philippoehrlein/kirby-navigation-groups#3]
Not sure if I misunderstood the purpose of this plugin.

I can add and edit groups, but can't figure out how to add internal Kirby page (or custom/external link, if that's possible) into the navigation root or even in the created group.

```yml
# site.yml, fresh starterkit
columns:
  - width: 1/2
    sections:

      testnavigation:
        type: fields
        fields:
          navigation:
            label: Navigation
            type: navigationgroups

      albums: sections/albums
```
I can see a request were made successfully to `http://starterkit-main.test/api/navigation-groups/pages?path=site&status=listed` 

```json
[
    {
        "id": "photography",
        "title": "Photography",
        "uuid": "photography",
        "path": "photography",
        "status": "listed",
        "permissions": {},
        "image": null
    },
    {
        "id": "notes",
        "title": "Notes",
        "uuid": "notes",
        "path": "notes",
        "status": "listed",
        "permissions": {},
        "image": null
    },
    {
        "id": "about",
        "title": "About us",
        "uuid": "about",
        "path": "about",
        "status": "listed",
        "permissions": {},
        "image": "http://starterkit-main.test/media/pages/about/322320f477-1742901505/table.jpg"
    }
]
```

<details><summary>Screenshots:</summary>
<p>

![Image](https://github.com/user-attachments/assets/ed274482-939a-4797-a54f-d7d0cc4dc44f)

![Image](https://github.com/user-attachments/assets/53c79c63-df02-4f08-8878-e592f53fda82)

![Image](https://github.com/user-attachments/assets/24bdab7b-98d8-43e4-986a-a35fe6bae92b)

</p>
</details> 

Kirby info:
```
{
  "info": {
    "kirby": "4.7.0",
    "php": "8.4.0",
    "server": "Apache/2.4.63 (Win64) OpenSSL/3.0.15 PHP/8.4.0",
    "license": "Unregistered",
    "languages": []
  },
  "security": [
    "The site is running locally with relaxed security checks",
    "Debugging must be turned off in production",
    "The Vue template compiler is enabled"
  ],
  "plugins": [
    {
      "name": "philippoehrlein/kirby-navigation-groups",
      "version": "1.1.2"
    }
  ]
}
```
